import { Injectable, Logger } from '@nestjs/common';
import { google } from 'googleapis';
import * as path from 'path';

@Injectable()
export class GoogleMeetService {
  private readonly logger = new Logger(GoogleMeetService.name);
  private calendar: any;

  constructor() {
    this.init();
  }

  private async init() {
    try {
      const clientEmail = process.env.GOOGLE_CLIENT_EMAIL;
      let privateKey = process.env.GOOGLE_PRIVATE_KEY;

      if (!clientEmail || !privateKey) {
        this.logger.warn('GOOGLE_CLIENT_EMAIL or GOOGLE_PRIVATE_KEY not set. Meet links cannot be auto-generated.');
        return;
      }

      // Handle multiline private key formatting issues from environment variables
      privateKey = privateKey.replace(/\\n/g, '\n');

      const auth = new google.auth.GoogleAuth({
        credentials: {
          client_email: clientEmail,
          private_key: privateKey,
        },
        scopes: ['https://www.googleapis.com/auth/calendar'],
      });
      const client = await auth.getClient();
      this.calendar = google.calendar({ version: 'v3', auth: client as any });
      this.logger.log('Google Calendar API initialized via Environment Variables');
    } catch (error) {
      this.logger.error('Failed to initialize Google Calendar API:', error);
    }
  }

  async createMeetLink(summary: string, description: string, startTime: Date, durationMinutes: number): Promise<string> {
    if (!this.calendar) {
      throw new Error('Google Calendar API not initialized');
    }

    const endTime = new Date(startTime.getTime() + durationMinutes * 60000);

    const event = {
      summary,
      description,
      start: {
        dateTime: startTime.toISOString(),
      },
      end: {
        dateTime: endTime.toISOString(),
      },
      conferenceData: {
        createRequest: {
          requestId: Math.random().toString(36).substring(7),
          conferenceSolutionKey: {
            type: 'hangoutsMeet',
          },
        },
      },
    };

    try {
      const response = await this.calendar.events.insert({
        calendarId: 'primary',
        resource: event,
        conferenceDataVersion: 1,
      });

      const link = response.data.hangoutLink;
      if (!link) {
        throw new Error('No Meet link generated by Google API');
      }

      return link;
    } catch (error) {
      this.logger.error('Error creating Google Meet event:', error);
      throw error;
    }
  }
}
